# Generated by Django 6.1 on 2026-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте фото продукта",
                null=True,
                upload_to="product/",
                verbose_name="Фото продукта",
            ),
        ),
    ]
